# Generated by Django 2.2.24 on 2021-06-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=50)),
                ('días_clase', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estudiantes', models.ManyToManyField(related_name='clases', to='estudiantes.Estudiante')),
            ],
        ),
    ]
