# Generated by Django 2.2.24 on 2021-06-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='días_clase',
            new_name='dias_clase',
        ),
    ]
